GET http://localhost:8080/profile
content-type: application/json


###
POST http://localhost:8080/profile
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OWJmMDBiYzllMThmYmE3MWU0YTBkMSIsImlhdCI6MTc3MTg0ODEzMSwiZXhwIjoxNzcxODUxNzMxfQ.txHWTtXcHaQ8sEcBNMUswL_NuowS9dkpciEj3egziHE

{
  "userId": "699bf00bc9e18fba71e4a0d1",
  "fullname": "Akshay Kumar",
  "bio": "Indian Actor",
  "profileImage": ""
}


###
PATCH http://localhost:8080/profile/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OWMzYzAwODI3ZGJiYTk1YzlmMzY0OCIsImlhdCI6MTc3MTg0NjczNywiZXhwIjoxNzcxODUwMzM3fQ.T6xjSNNECAl9cfZu1ii7ZGHv3fmMkmSmXeZpCHX24gU

{
  "bio": "Prime Minister of India."
}


###
DELETE http://localhost:8080/profile/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OWMzYzAwODI3ZGJiYTk1YzlmMzY0OCIsImlhdCI6MTc3MTg0NjczNywiZXhwIjoxNzcxODUwMzM3fQ.T6xjSNNECAl9cfZu1ii7ZGHv3fmMkmSmXeZpCHX24gU