GET http://localhost:8080/profile
content-type: application/json


###
POST http://localhost:8080/profile
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OWMwNWY4OTZhYjEzODYyMjJiYzMyYiIsImlhdCI6MTc3MTgzMjgzNiwiZXhwIjoxNzcxODM2NDM2fQ.9sxiWHi7x3ZmPav8FRn4Y8OX65Wxd-UaO_8A30MFHXg

{
  "userId": "699befb6c9e18fba71e4a0ca",
  "fullname": "Test Test",
  "bio": "Only for Test.",
  "profileImage": ""
}


###
PATCH http://localhost:8080/profile/699c05f896ab1386222bc32b
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OWMwNWY4OTZhYjEzODYyMjJiYzMyYiIsImlhdCI6MTc3MTgzMjgzNiwiZXhwIjoxNzcxODM2NDM2fQ.9sxiWHi7x3ZmPav8FRn4Y8OX65Wxd-UaO_8A30MFHXg

{
  "bio": "This is only Test"
}


###
DELETE http://localhost:8080/profile/699c05f896ab1386222bc32b
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OWMwNWY4OTZhYjEzODYyMjJiYzMyYiIsImlhdCI6MTc3MTgzMjgzNiwiZXhwIjoxNzcxODM2NDM2fQ.9sxiWHi7x3ZmPav8FRn4Y8OX65Wxd-UaO_8A30MFHXg